/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package adivinanumero;

import java.awt.Color;
import java.util.Random;
import javax.swing.JOptionPane;

/**
 *
 * @author Usuario
 */
public class VentanaNumero extends javax.swing.JFrame {
    Random numAleatorio = new Random();
        int randomico = numAleatorio.nextInt(1000);

    /**
     * Creates new form VentanaNumero
     */
    public VentanaNumero() {
        initComponents();
        System.out.println("El numero se ha generado"+randomico);
        this.getContentPane().setBackground(Color.yellow);
        
        
    } 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo = new javax.swing.JLabel();
        lblMensaje = new javax.swing.JLabel();
        txtIntento = new javax.swing.JTextField();
        lblAviso = new javax.swing.JLabel();
        btnJugar = new javax.swing.JButton();
        btnIntento = new javax.swing.JButton();
        btnexit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTitulo.setText("JUGUEMOS A ADIVINAR EL NUMERO");

        lblMensaje.setText("Tengo un numero entre 1 y 1000. Puede usted adivinarlo?  Por favor escriba su primer intento.");

        txtIntento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIntentoActionPerformed(evt);
            }
        });

        btnJugar.setText("Volver a jugar");
        btnJugar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnJugarActionPerformed(evt);
            }
        });

        btnIntento.setText("Intentar");
        btnIntento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIntentoActionPerformed(evt);
            }
        });

        btnexit.setText("Salir");
        btnexit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnexitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblAviso, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(455, 455, 455))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(lblMensaje))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(lblTitulo))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnIntento)
                            .addComponent(txtIntento, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(btnJugar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(115, 115, 115)
                        .addComponent(btnexit)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblMensaje)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtIntento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblAviso, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnIntento))
                .addGap(18, 18, 18)
                .addComponent(btnJugar)
                .addGap(18, 18, 18)
                .addComponent(btnexit)
                .addContainerGap(113, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIntentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIntentoActionPerformed
      if(datos()==true){
        String ingreso = txtIntento.getText();
        int numero= Integer.parseInt(ingreso);
        if(numero==randomico){
             
       lblMensaje.setText("Correcto!");
        txtIntento.setEditable(false); 
         this.getContentPane().setBackground(Color.green);
            
        }else if(numero<randomico){
            lblAviso.setText("Muy bajo!");
            this.getContentPane().setBackground(Color.red);   
        }else if(numero>randomico){
            lblAviso.setText("Muy alto!");
             this.getContentPane().setBackground(Color.blue);
           
        }
      }else {
          JOptionPane.showMessageDialog(rootPane,"Ingrese un numero");
      }
        
    }//GEN-LAST:event_btnIntentoActionPerformed

    private void btnJugarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnJugarActionPerformed
         randomico = numAleatorio.nextInt(1000); 
         System.out.println("Numero generado:" + randomico);
         this.getContentPane().setBackground(Color.yellow);
        txtIntento.setEditable(true);
        txtIntento.setText("");
        lblAviso.setText("");
        lblMensaje.setText("Tengo un numero entre 1 y 1000. Puede usted adivinarlo?  Por favor escriba su primer intento.");
    }//GEN-LAST:event_btnJugarActionPerformed

    private void btnexitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnexitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnexitActionPerformed

    private void txtIntentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIntentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIntentoActionPerformed

    /**
     * @param args the command line arguments
     */ 
    public boolean datos (){
    boolean confirmacion = true;
    if(txtIntento.getText().equals("")){ 
        confirmacion=false;
         return confirmacion;
    } else { 
        return true;
        }
       
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIntento;
    private javax.swing.JButton btnJugar;
    private javax.swing.JButton btnexit;
    private javax.swing.JLabel lblAviso;
    private javax.swing.JLabel lblMensaje;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JTextField txtIntento;
    // End of variables declaration//GEN-END:variables
}
